### ISSUE TITLE
Set long text to inputTextView height constraint bug

### ISSUE THREAD

**Issue by lordcodes** [nathantannar4/InputBarAccessoryView#41]
I am having an issue with the inputBarAccessoryView within an app.

We need to set a draft message that was previously stored. This is done using:

```
inputBar.inputTextView.text = draftMessage
```

In our app this causes the inputBarTextView to grow past the top of the screen (going underneath status bar) and the inputBarTextView is left unscrollable so you cannot scroll within it. However, when I reproduced this in the example app, the box doesn't go beyond the maximum height, however, it is still not scrollable, so the same issue has been encountered.

If you look in the console when this happens, it is due to some conflicting constraints and so the end result in UI depends on which constraints the system decides to break.

```
2018-10-22 14:01:14.392632+0100 Example[63316:4832764] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600003df63f0 UIView:0x7fb4e6e4a740.bottom == UILayoutGuide:0x6000027c55e0'UIViewSafeAreaLayoutGuide'.bottom - 6   (active)>",
    "<NSLayoutConstraint:0x600003df63a0 V:|-(0)-[InputBarAccessoryView.InputStackView:0x7fb4e6e55c40]   (active, names: '|':Example.iMessageInputBar:0x7fb4e6e47a40 )>",
    "<NSLayoutConstraint:0x600003df6350 InputBarAccessoryView.InputStackView:0x7fb4e6e55c40.bottom == UIView:0x7fb4e6e4a740.top - 6   (active)>",
    "<NSLayoutConstraint:0x600003dda300 '_UITemporaryLayoutHeight' Example.iMessageInputBar:0x7fb4e6e47a40.height == 0   (active)>",
    "<NSLayoutConstraint:0x600003df5e00 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x6000027c55e0'UIViewSafeAreaLayoutGuide']-(0)-|   (active, names: '|':Example.iMessageInputBar:0x7fb4e6e47a40 )>"
)
```

To reproduce in example app, I set long text at the end of `viewDidLoad` within `CommonTableViewController`.

```
inputBar.inputTextView.text = """
"""
```

I pasted about 10 paragraphs of lorum ipsum within the string.

**Comment by nathantannar4** [comment]
Interesting, I can reproduce this in `viewDidLoad` however now in `viewDidAppear`. I stepped through the layout and `isScrollEnabled` is toggled to true, but indeed it doesn't work

**Comment by nathantannar4** [comment]
Ok, I wanna say this is a UIKit bug? Unless my layout somewhere is breaking something. Ive turned off all toggling of `isScrollEnabled` so its always equal to `true` and the scroll still seems to be locked

**Comment by nathantannar4** [comment]
Interesting, for some reason I believe the placeholder label constraints were interfering with the scrollview of the InputTextView

When deactivating the constraints, no issue. Wonder what the root cause is 
```
@objc
    private func textViewTextDidChange() {
        let isPlaceholderHidden = !text.isEmpty
        placeholderLabel.isHidden = isPlaceholderHidden
        if isPlaceholderHidden {
            placeholderLabelConstraintSet?.deactivate()
        } else {
            placeholderLabelConstraintSet?.activate()
        }
    }
```

**Comment by nathantannar4** [comment]
I think its due to the content size of the scrollview being ambiguous

**Comment by lordcodes** [comment]
Thanks for looking, I had a look before I reported it and tried to fix it, but was unsuccessful.

The result is different in the example app and mine. In my app the inputbartextview grows taller than the screen!

My initial thoughts were that it must relate to the scroll view content size. I have seen issues with this in other scroll views.

**Comment by nathantannar4** [comment]
I didn't have mine grow taller than the screen. If yours is did you modify the maxtextviewheight? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lordcodes** [comment]
No, I don't think so.

When the constraints conflicted, the system broke the height constraint on
the text view. However, in example app it broke one of the other
constraints. This results in slightly different resulting UI behaviour
between the two.

**Comment by nathantannar4** [comment]
I fixed the breaking constraints but it still never got bigger than the screen

**Comment by lordcodes** [comment]
It only got taller than the screen because of the system deleting the
height constraint. If the constraints have been fixed this wouldn't happen
anymore.

**Comment by nathantannar4** [comment]
Should be fixed in 4.1.0 which I just released

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gizmeondev** [comment]
Hi, I am still getting this issue when pasting a long text. But this does not occur while typing. The input bar goes on over the top of the screen.
version using: 4.2.2

**Comment by hamedazhar-giz** [comment]
Hi, I am still getting this issue when pasting a long text. But this does not occur while typing. The input bar goes on over the top of the screen. 
version using: 4.2.2

**Comment by nathantannar4** [comment]
Can you please provide some more details on how to reproduce this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
